name: RaheimSmith
favicon: null
layout_spectrum: 0.26498220511712134
typography_spectrum: 0.35797
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8125
  lightness: 0.5690815253183246
  saturation: 0.9489181188400835
  rhythmicContrast: 0.656416239682585
purpose: []
